### ISSUE TITLE
Releases of paramcoq are spread out across many repositories

### ISSUE THREAD

**Issue by palmskog** [coq-community/paramcoq#28]
Past releases of paramcoq are spread out across several repositories and their forks, e.g., [this one](https://github.com/aa755/paramcoq). This is highly inconvenient for users and packaging.

Is there any chance we can get all past releases archived on the same repository (this one) and the old repositories marked as obsolete?

**Comment by proux01** [comment]
Other repositories clearly indicate "forked from coq-community/paramcoq"
whereas recent opam packages indicate "dev-repo:    "git+https://github.com/coq-community/paramcoq.git""
What else do you expect?

**Comment by palmskog** [comment]
At least to me, one of the goals of Coq-community is to make both past and present releases of Coq projects easy to find for researchers (in one place). Replicating the releases found in paramcoq forks here would accomplish that.

**Comment by proux01** [comment]
Done

However, it's kind of a mess as Github orders releases by order of creation, meaning the, newly readded, old releases are listed first.

**Comment by Zimmi48** [comment]
I don't know exactly what @palmskog had in mind but I wouldn't have gone as far as creating the releases using GitHub's feature, I would have just imported the tag. To me, it seems that it would have been sufficient. And then, if the tags are not annotated, they do not have a date on their own and only have the date of the corresponding commit, and thus are correctly ordered. And if the tags are annotated but were created in the other repo at an earlier date, and then imported, they should still be correctly ordered by GitHub.

**Comment by proux01** [comment]
Unfortunately, there were small differences between the two repositories and I had to recreate some tags (and even cherry pick a few commits) so the tags are already incorrectly ordered. But thanks for the idea.

**Comment by Zimmi48** [comment]
OK, but even if you recreate the tags, if you choose to create non-annotated tags (no `-a` and no `-s`), they are ordered by commit dates, not tagging date IINM.

**Comment by proux01** [comment]
Thanks, @Zimmi48 , that did work! (well, I also had to use `-s` and the env variable `GIT_COMMITTER_DATE` in a few cases)

**Comment by Zimmi48** [comment]
Indeed, that's also a good technique.
