### ISSUE TITLE
Anomaly "Uncaught exception Not_found."

### ISSUE THREAD

**Issue by ybertot** [coq-community/paramcoq#42]
Hello, I am using coq-8.9, math-comp-1.9.0, and coq-paramcoq-1.1.1+coq8.9
The following program raises an anomaly:
<pre>
From mathcomp Require Import all_ssreflect.

Declare ML Module "paramcoq".

Section seq_algorithm.

Definition trigger (P : Type) (s : seq P) (p0 : P) : P :=
  if size s <= 0 then p0 else p0.

End seq_algorithm.

Parametricity seq.
Parametricity bool.
Parametricity nat.
Parametricity trigger.
</pre>

**Comment by proux01** [comment]
Thanks for reporting!

I can reproduce and will investigate but cannot promise anything before next week.

In the meantime, replacing all your `Parametricity` commands by
```coq
Parametricity Recursive trigger.
Parametricity trigger.
```
seems to work better.

There are pending proof obligations, you can handle them with a `Parametricity Tactic` as in https://github.com/coq-community/paramcoq/blob/master/test-suite/Parametricity.v
