### ISSUE TITLE
Parametricity Recursive doesn't recognize dependence in Inductives/Records

### ISSUE THREAD

**Issue by aa755** [coq-community/paramcoq#5]
```
Declare ML Module "paramcoq".

Parametricity Recursive plus. (*success *)

Record GenericTermSig (Opid : Type) : Type := Build_GenericTermSig
  { OpBindings : Opid -> list nat }.

Fail Parametricity Recursive GenericTermSig.
(*
DepRefs:
GenericTermSig
The command has indeed failed with message:
Error: The inductive 'Coq.Init.Datatypes.list' has no registered translation.
*)

Parametricity Recursive list.

Parametricity Recursive GenericTermSig. (*succcess *)
```

I enabled printing of dependencies here:
https://github.com/aa755/paramcoq/commit/7e4c603d7fc013544cf129fa3bf38e685be3bd9b

**Comment by mlasson** [comment]
Yes, it was fixed in https://github.com/coq/coq/commit/6a1fb5ffbb9fd63fc0c2445b9391229a959e3608.
If it is really a problem, we could reimplement the computation of dependencies (instead of using coqlib's function).

**Comment by aa755** [comment]
Indeed, the problem is gone in Coq 8.6.
I have managed to port paramcoq to Coq 8.6. The port is available at:
https://github.com/aa755/paramcoq/commits/v86

Perhaps we should keep separate branches for Coq 8.5 and Coq 8.6 for now.
If so, I can send a pull request if you create an 8.6 branch. Alternatively, you can clone the above branch to this repository.
