### ISSUE TITLE
Branch for 8.14

### ISSUE THREAD

**Issue by palmskog** [coq-community/paramcoq#73]
The `master` branch of Paramcoq no longer builds with Coq's `v8.14` branch. Yet, the release of 8.14.0 is on the horizon, and I would *really* like the corresponding Paramcoq release to include the improvements from #70, #71, and #72.

@proux01 do you mind if I push a branch `v8.14` here based on 1d9409b9eb (the last commit that builds with Coq's `v8.14`) with changes from the PRs on top?

**Comment by proux01** [comment]
That would be nice indeed (sorry I'm a bit late on this, I was disturbed by the fact that 8.14 seems in a kind of zombie state this summer).
I'll then release `1.1.3+coq8.14` as soon as 8.14 is out.

**Comment by palmskog** [comment]
I pushed the [branch](https://github.com/coq-community/paramcoq/tree/v8.14). However, due to coq-community/docker-coq#29 I can't use any Docker CI there, so I resort to Nix. This should probably be fixed back once the Docker-Coq issue is resolved, since I don't know any way to run the tests in Nix.

**Comment by palmskog** [comment]
Oh and as a memento, I used the [this approach](https://gist.github.com/katylava/564416) to perform a selective merge. Since I was the author of all the non-merge commits in `master` that "disappeared" in the v8.14 branch, this doesn't lose any contribution information.

**Comment by palmskog** [comment]
@proux01 maybe I could push analogous changes to v8.13 as well? If you then make a release `1.1.3+coq8.13` at the same time as `1.1.3+coq814`, we could declare #56 solved (at least in this repo, maybe it should be reported upstream).

**Comment by proux01** [comment]
Sure, feel free to.

**Comment by palmskog** [comment]
OK, I'm done with v8.13 and v8.14. I took the liberty to push a minimal metadata-only update to `master`. Will keep this issue open until we have full CI for v8.14, though, which may take a week or two.

**Comment by proux01** [comment]
Great, thanks! I'll release `1.1.3+coq8.13` together with `1.1.3+coq8.14`.

**Comment by proux01** [comment]
I'm closing this now that we have OPAM packages.
