### ISSUE TITLE
Release compatible with Coq 8.15

### ISSUE THREAD

**Issue by pi8027** [coq-community/paramcoq#90]
Can we have a release of Paramcoq compatible with Coq 8.15(+rc1) soon?

FTR (since @proux01 is also a maintainer of CoqEAL), I'm using the combination of CoqEAL 1.1.0, the v8.15 branch of Paramcoq, and Coq 8.15+rc1 without any issue except that I have to pass `--ignore-constraints-on coq` to OPAM.

**Comment by proux01** [comment]
As soon as we get a Docker image for the CI, I'll release a `1.1.3+coq8.15` in OPAM extra-dev repo.
Cc @erikmd

**Comment by erikmd** [comment]
> As soon as we get a Docker image for the CI, I'll release a `1.1.3+coq8.15` in OPAM extra-dev repo.

@proux01

* Done in PR https://github.com/coq-community/docker-coq/pull/42

**Comment by pi8027** [comment]
Thanks!
